version: 0
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run: ls -lah
      - run: ./gradlew sonarqube \
  -Dsonar.projectKey=cumal_MyDoor \
  -Dsonar.organization=cumal-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=c8013ba71574aaf84edaaf67c8470546bce85cce
